name: LignumReload
version: '${project.version}'
author: TermalQuake
website: lignum.su
main: me.lignumreload.main
api-version: 1.19
commands:
  ligreload:
    description: Перезагрузить плагины
    usage: /ligreload
